language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo fmt -- --check

  # Check "no default features"
  - cargo build --verbose --workspace --exclude binary_size --no-default-features

  # Check "full/blocking"
  - cargo build --verbose --workspace --exclude binary_size
  - cargo test --verbose --workspace --exclude binary_size